name: Notify MSL Bundle Repository

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository name
        id: repo-name
        run: echo "repo=${{ github.repository }}" >> $GITHUB_OUTPUT

      - name: Trigger Meta Repository Workflow
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.MSL_BUNDLE_REPO_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'harmonicinc-video',
              repo: 'ng-msl-bundle',
              workflow_id: 'update-meta.yaml',
              ref: 'main',
              inputs: {
                repo: '${{ steps.repo-name.outputs.repo }}',
                version: '${{ github.event.release.tag_name }}'
              }
            });
